openapi: 3.0.3
info:
  title: Приложение для обучения
  description: "Приложение созданное для упрощения жизни студентам и улучшения образовательного процесса, позволяет просматривать расписание занятий, общаться со студентами и преподавателями, получать уникальный qr для прохода через турникеты в университет, выкладывать домашние задания для студентов и отправлять преподавателю ответы на задания"
  version: 0.0.1
servers:
  - url: https://localhost:8080/api/v1/
    description: Dev server
paths:
  #/users:
  #  post:
  #      summary: Добавление нового пользователя
  #      description: Метод предназначен для сохранения в БД данных о новом пользователе.
  #      operationId: createUser
  #      tags:
  #        - Users
  #      requestBody:
  #        required: true
  #        content:
  #          application/json:
  #            schema:
  #              $ref: "#/components/schemas/User"
  #      responses:
  #        '200':
  #          description: Подтверждение успешного сохранения
  #          content:
  #            application/json:
  #              schema:
  #                $ref: "#/components/schemas/User"
  #        '400':
  #          description: Некорректные входные данные. Возвращает список атрибутов с ошибками
  #          content:
  #            application/json:
  #              schema:
  #                type: array
  #                items:
  #                  type: string
  /users/{id}:
    get:
      summary: Получение пользователя
      description: Метод для получения пользователя
      operationId: getUserId
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор пользователя
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
          schema:
            type: string
            format: uuid
      responses:
          '200':
            description: Пользователь
            content:
              application/json:
                schema:
                  items:
                    $ref: "#/components/schemas/User"
    put:
        summary: Метод обновления информации о пользователе
        description: Метод предназначен для обновления в БД даты рождения и ФИ пользователя
        operationId: updateUser
        tags:
          - User
        parameters:
          - name: id
            in: path
            required: true
            description: Идентификатор пользователя
            example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
            schema:
              type: string
              format: uuid
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        responses:
          '200':
            description: Подтверждение успешного обновления
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/User"
          '400':
            description: Некорректные входные данные. Возвращает список атрибутов с ошибками
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
          '5XX':
            description: Любая неожиданная ошибка сервера
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error" ##!!!!!
  /student_schedule:
    get:
      summary: Получение списка занятий
      description: Возвращает список занятий для указанной группы и даты.
      operationId: getStudentSchedule
      tags:
        - Schedules
      parameters:
        - name: date
          in: query
          required: true
          description: Дата занятий
          schema:
            type: string
            format: date
          example: 2024-11-19
        - name: group
          in: query
          required: true
          description: Группа студента
          schema:
            type: string
            example: ИВ-222
      responses:
        '200':
          description: Успешное получение списка занятий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Class"
        '400':
          description: Некорректные параметры запроса
  /student_schedule/{id}:
    get:
      summary: Получение занятия по ID на экране расписания
      description: Возвращает информацию о конкретном занятии на основе его идентификатора.
      operationId: getStudentScheduleById
      tags:
        - Schedules
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор занятия
          schema:
            type: string
            format: uuid
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
      responses:
        '200':
          description: Успешное получение информации о занятии
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Class"
        '400':
          description: Некорректные параметры запроса
        '404':
          description: Занятие не найдено
  /student_scheduleById:
    get:
      summary: Получение занятия по ID на экране занятия / задания
      description: Метод для получения занятия по указанным параметрам.
      operationId: getStudentScheduleByIds
      tags:
        - Schedule
      parameters:
        - name: id
          in: query
          required: true
          description: Идентификатор занятия
          schema:
            type: string
        - name: date
          in: query
          required: true
          description: Дата занятия
          schema:
            type: string
            format: date
        - name: group
          in: query
          required: true
          description: Группа студента
          schema:
            type: string
        - name: start_time
          in: query
          required: true
          description: Время начала занятия
          schema:
            type: string
            format: time
      responses:
        '200':
          description: Успешное получение занятия
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Class'
        '400':
          description: Некорректные параметры запроса
        '404':
          description: Занятие не найдено
  /student_responseById:
    post:
      summary: Отправка ответа на задание
      description: Метод для отправки ответа на задание.
      operationId: postStudentResponseById
      tags:
        - Response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentResponse'
      responses:
        '200':
          description: Успешная отправка ответа
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ответ успешно отправлен
        '400':
          description: Некорректные параметры запроса
  /teacher_schedule:
    get:
      summary: Получение расписания преподавателя на текущую дату
      description: Возвращает список занятий преподавателя на заданную дату. Для каждого занятия отображаются основные данные, такие как название предмета, группа, время начала и окончания, тип занятия и аудитория.
      operationId: getTeacherSchedule
      tags:
        - Schedules
      parameters:
        - name: date
          in: query
          required: true
          description: Дата для получения расписания (формат YYYY-MM-DD)
          schema:
            type: string
            format: date
          example: 2024-11-19
        - name: teacher_id
          in: query
          required: true
          description: ID преподавателя
          schema:
            type: string
            format: uuid
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
      responses:
        '200':
          description: Успешное получение расписания преподавателя
          content:
            application/json:
              schema:
                type: object
                properties:
                  classes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Class'
        '400':
          description: Некорректные параметры запроса
        '404':
          description: Расписание не найдено
  /teacher_scheduleById:
    get:
      summary: Получение информации о занятии и задании по ID
      description: Возвращает информацию о конкретном занятии и соответствующем задании на основе ID занятия, даты и ID преподавателя.
      operationId: getTeacherScheduleById
      tags:
        - Schedule
      parameters:
        - name: id
          in: query
          required: true
          description: ID занятия
          schema:
            type: string
            format: uuid
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        - name: date
          in: query
          required: true
          description: Дата занятия
          schema:
            type: string
            format: date
          example: "2024-11-19"
        - name: teacher_id
          in: query
          required: true
          description: ID преподавателя
          schema:
            type: string
            format: uuid
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
      responses:
        '200':
          description: Успешное получение информации о занятии и задании
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Class'
        '400':
          description: Некорректные параметры запроса
        '404':
          description: Занятие не найдено
  /teacher_responseById:
    patch:
      summary: Оценка ответа студента
      description: Метод для оценки ответа студента на задание. Преподаватель может поставить оценку за выполненное задание.
      operationId: patchTeacherResponseById
      tags:
        - Response
      parameters:
        - name: id
          in: query
          required: true
          description: ID занятия
          schema:
            type: string
            format: uuid
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        - name: student_id
          in: query
          required: true
          description: ID студента
          schema:
            type: string
            format: uuid
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        - name: date
          in: query
          required: true
          description: Дата занятия
          schema:
            type: string
            format: date
          example: 2024-11-19
        - name: group
          in: query
          required: true
          description: Группа студента
          schema:
            type: string
          example: ИВ-222
        - name: start_time
          in: query
          required: true
          description: Время начала занятия
          schema:
            type: string
            format: time
        - name: mark
          in: query
          required: true
          description: Оценка за выполненное задание
          schema:
            type: integer
          example: 4
      responses:
        '200':
          description: Успешная отправка оценки
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Оценка успешно отправлена"
        '400':
          description: Некорректные параметры запроса
        '404':
          description: Ответ или занятие не найдено
  /electronic_pass:
    get:
      summary: Получение электронного пропуска в виде QR-кода
      description: Возвращает уникальный QR код для студента или преподавателя, который обновляется ежедневно. QR код генерируется на основе student_id или teacher_id и используется для прохода через турникеты.
      operationId: getElectronicPass
      tags:
        - Pass
      parameters:
        - name: user_id
          in: query
          required: true
          description: ID студента или преподавателя
          schema:
            type: string
            format: uuid
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        - name: user_type
          in: query
          required: true
          description: Тип пользователя (student или teacher)
          schema:
            type: string
            enum:
              - student
              - teacher
          example: student
      responses:
        '200':
          description: Успешное получение QR-кода
          content:
            application/json:
              schema:
                type: object
                properties:
                  qr_code:
                    type: string
                    description: Строка, представляющая QR код
                    example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA..."
        '400':
          description: Некорректные параметры запроса
        '404':
          description: Пользователь не найден

components:
  schemas:
    User:
      type: object
      required:
        - surname
        - name
        - role
        - phone
        - email
        - birthdate
        - password
      properties:
            user_id:
              type: string
              format: uuid
              example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
            surname:
              type: string
              description: Фамилия пользователя, только буквы русского алфавита, первая буква заглавная, не более 50 символов
              pattern: '^[А-ЯЁ][а-яё]{1,50}$'
              example: Городилов
            name:
              description: Имя пользователя, только буквы русского алфавита, первая буква заглавная, не более 50 символов
              type: string
              pattern: '^[А-ЯЁ][а-яё]{1,50}$'
              example: Павел
            role:
              description: Роль пользователя - студент/преподаватель
              type: string
              example: Студент
            phone:
              description: Номер телефона пользователя, состоит из 11 цифр, начинается с 7
              type: integer
              pattern: '^8\d{10}$'
              example: 89136663322
            email:
              description: Электронная почта пользователя
              type: string
              example: Pavel04072004@gmail.com
            birthdate:
              description: День рождения пользователя
              type: string
              example: 04.07.04
            password:
              description: Пользовательский пароль, от 8 до 64 символов. Только латинские буквы, цифры и знаки '!?'. Обязательно наличие минимум 1 буквы верхнего и нижнего регистра, цифры и знака
              type: string
              pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!?])[A-Za-z\d!?]{8,64}$'
              example: Fafwsgsd!322
    UserUpdate:
      type: object
      properties:
        lastName:
          type: string
          description: Фамилия
          pattern: '^[А-ЯЁ][а-яё]{1,50}$'
          example: Городилов
        firstName:
          type: string
          description: Имя
          pattern: '^[А-ЯЁ][а-яё]{1,50}$'
          example: Павел
        birthdate:
            type: string
            description: Дата рождения
            format: string
            example: 04.07.2004
    Class:
      type: object
      properties:
        subject:
          type: string
          description: Предмет
          example: СТП
        start_time:
          type: string
          format: time
          description: Время начала занятия
          example: 08:00
        end_time:
          type: string
          format: time
          description: Время окончания занятия
          example: 09:35
        type:
          type: string
          description: Характеристика занятия по его формату
          enum:
            - lecture
            - practical
          example: Лекция
        teacher:
          type: string
          description: Преподаватель который ведет предмет
          example: Иван Иванович Иванов
        classroom:
          type: string
          description: Номер аудитории
          example: 202
        task:
          type: string
          description: Задание на занятие
          example: Выполнить лабораторную №2
        header:
          type: string
          description: Заголовок задания
          example: Создать REST API
        body:
          type: string
          description: Что необходимо сделать по заданию
          example: Вам необходимо...
        responses:
          type: array
          items:
            $ref: '#/components/schemas/Response'
    Response:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID ответа
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        student_id:
          type: string
          format: uuid
          description: ID студента
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        response_type:
          type: string
          description: Тип ответа
          enum:
            - text
            - file
        body:
          type: string
          description: Текст ответа или ссылка на файл
        mark:
          type: number
          format: int
          description: Оценка за задание
          example: 4
    StudentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID задания
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        student_id:
          type: string
          format: uuid
          description: ID студента
          example: 42abcd2b-8b9c-4af9-88f7-0bc180cf74b4
        response_type:
          type: string
          description: Тип ответа
          enum:
            - text
            - file
        body:
          type: string
          description: Текст ответа или ссылка на файл
    Error:
      type: object
      required:
        - code
        - massege
      properties:
        code:
          type: integer
          description: Код ошибки
          example: 501
        massege:
          type: string
          description: Сообщение ошибки
          example: Ошибка ответа сервера