name: Docker Image CI

on:
  push:
    branches: [ "docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradle
        run: chmod +x ./gradlew

      - name: Build .jar file
        run: ./gradlew docker

      - name: Build docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_NAME/app:latest ./src/main/resources

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag ghcr.io/$REPO_NAME/app:latest ghcr.io/$REPO_NAME/app:latest
          docker push ghcr.io/$REPO_NAME/app:latest

      - name: Trigger deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}